### ISSUE TITLE
Develop branch is broken

### ISSUE THREAD

**Issue by alexbruy** [dtarb/TauDEM#154]
I tried to improve build system a bit in `Develop` branch, but looks like it is broken

```
In file included from /home/alex/devel/TauDEM/src/commonLib.h:101:0,
                 from /home/alex/devel/TauDEM/src/tiffIO.h:49,
                 from /home/alex/devel/TauDEM/src/tiffIO.cpp:47:
/home/alex/devel/TauDEM/src/linearpart.h: In member function ‘void linearpart<datatype>::savedxdyc(tiffIO&)’:
/home/alex/devel/TauDEM/src/linearpart.h:523:16: error: invalid use of incomplete type ‘class tiffIO’
      dxc[i]=obj.getdxc(globalY);
                ^
In file included from /home/alex/devel/TauDEM/src/linearpart.h:42:0,
                 from /home/alex/devel/TauDEM/src/commonLib.h:101,
                 from /home/alex/devel/TauDEM/src/tiffIO.h:49,
                 from /home/alex/devel/TauDEM/src/tiffIO.cpp:47:
/home/alex/devel/TauDEM/src/partition.h:46:7: note: forward declaration of ‘class tiffIO’
 class tiffIO;
       ^
In file included from /home/alex/devel/TauDEM/src/commonLib.h:101:0,
                 from /home/alex/devel/TauDEM/src/tiffIO.h:49,
                 from /home/alex/devel/TauDEM/src/tiffIO.cpp:47:
/home/alex/devel/TauDEM/src/linearpart.h:524:13: error: invalid use of incomplete type ‘class tiffIO’
   dyc[i]=obj.getdyc(globalY);
             ^
In file included from /home/alex/devel/TauDEM/src/linearpart.h:42:0,
                 from /home/alex/devel/TauDEM/src/commonLib.h:101,
                 from /home/alex/devel/TauDEM/src/tiffIO.h:49,
                 from /home/alex/devel/TauDEM/src/tiffIO.cpp:47:
/home/alex/devel/TauDEM/src/partition.h:46:7: note: forward declaration of ‘class tiffIO’
 class tiffIO;
```

**Comment by dtarb** [comment]
What system and compiler are you working on.  I just verified that I am able to rebuild and successfully execute the test suite on a PC.  This Tiffio class has been successfully used for a while and has not changed recently.

**Comment by alexbruy** [comment]
I'm on LInux. Trying to build with GCC 5.4.0 got error posted in the first message.

**Comment by dtarb** [comment]
Does your pull request #155 resolve this, or is this still a problem.

**Comment by alexbruy** [comment]
#155 is a completely dufferent thing, it is about missed tools in the CMakeLists.txt

**Comment by dtarb** [comment]
OK.  I do not know how to change the code to fix this, and it works for my current PC visual studio setup.

**Comment by twilkinson** [comment]
Hi @alexbruy, did you ever get a solution to this problem?  I'm running into the same thing trying to build the `Develop` branch on Linux (CentOS 7.4).

In fact, even to get this far, I've also had to work around https://github.com/dtarb/TauDEM/issues/166 by removing all references to `SetRegion `and `SetRegionmn `in `CMakeLists.txt`.

Any suggestions?

Terry

**Comment by twilkinson** [comment]
@dtarb , what version of Linux are you using?  Are you using any special compiler switches?  I'm using Ubuntu 14.04 LTS and with default installation of C and C++.

I cloned a new copy of the Develop branch, did the cmake, and make as follows, and I'm getting these errors (same as @alexbruy describes above in the OP).  It seems to be having trouble compiling **tiffIO.cpp**

    vagrant@vagrant-ubuntu-trusty-64:~/TauDEM-Develop/src/build$ cmake ..
    -- The C compiler identification is GNU 4.8.4
    -- The CXX compiler identification is GNU 4.8.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so;/usr/lib/x86_64-linux-gnu/libopa.so;/usr/lib/x86_64-linux-gnu/libmpl.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr
    /lib/libcr.so;/usr/lib/x86_64-linux-gnu/libpthread.so
    -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so;/usr/lib/x86_64-linux-gnu/libopa.so;/usr/lib/x86_64-linux-gnu/libmpl
    .so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/libcr.so;/usr/lib/x86_64-linux-gnu/libpthread.so
    -- Found GDAL: /usr/lib/libgdal.so
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/vagrant/TauDEM-Develop/src/build

        vagrant@vagrant-ubuntu-trusty-64:~/TauDEM-Develop/src/build$ make
    Scanning dependencies of target aread8
    [  0%] Building CXX object CMakeFiles/aread8.dir/aread8mn.cpp.o
    [  1%] Building CXX object CMakeFiles/aread8.dir/aread8.cpp.o
    [  1%] Building CXX object CMakeFiles/aread8.dir/commonLib.cpp.o
    [  2%] Building CXX object CMakeFiles/aread8.dir/tiffIO.cpp.o
    In file included from /home/vagrant/TauDEM-Develop/src/commonLib.h:102:0,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.h:49,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:47:
    /home/vagrant/TauDEM-Develop/src/linearpart.h: In member function ‘void linearpart<datatype>::savedxdyc(tiffIO&)’:
    /home/vagrant/TauDEM-Develop/src/linearpart.h:523:16: error: invalid use of incomplete type ‘class tiffIO’
          dxc[i]=obj.getdxc(globalY);
                    ^
    In file included from /home/vagrant/TauDEM-Develop/src/linearpart.h:42:0,
                     from /home/vagrant/TauDEM-Develop/src/commonLib.h:102,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.h:49,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:47:
    /home/vagrant/TauDEM-Develop/src/partition.h:46:7: error: forward declaration of ‘class tiffIO’
     class tiffIO;
           ^
    In file included from /home/vagrant/TauDEM-Develop/src/commonLib.h:102:0,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.h:49,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:47:
    /home/vagrant/TauDEM-Develop/src/linearpart.h:524:13: error: invalid use of incomplete type ‘class tiffIO’
       dyc[i]=obj.getdyc(globalY);
                 ^
    In file included from /home/vagrant/TauDEM-Develop/src/linearpart.h:42:0,
                     from /home/vagrant/TauDEM-Develop/src/commonLib.h:102,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.h:49,
                     from /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:47:
    /home/vagrant/TauDEM-Develop/src/partition.h:46:7: error: forward declaration of ‘class tiffIO’
     class tiffIO;
           ^
    /home/vagrant/TauDEM-Develop/src/tiffIO.cpp: In member function ‘void tiffIO::read(long int, long int, long int, long int, void*)’:
    /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:250:8: warning: ignoring return value of ‘CPLErr GDALRasterIO(GDALRasterBandH, GDALRWFlag, int, int, int, int, void*, int
    , int, GDALDataType, int, int)’, declared with attribute warn_unused_result [-Wunused-result]
       0, 0);
            ^
    /home/vagrant/TauDEM-Develop/src/tiffIO.cpp: In member function ‘void tiffIO::write(long int, long int, long int, long int, void*)’:
    /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:370:9: warning: ignoring return value of ‘CPLErr GDALRasterIO(GDALRasterBandH, GDALRWFlag, int, int, int, int, void*, int
    , int, GDALDataType, int, int)’, declared with attribute warn_unused_result [-Wunused-result]
        0, 0);
             ^
    /home/vagrant/TauDEM-Develop/src/tiffIO.cpp:408:9: warning: ignoring return value of ‘CPLErr GDALRasterIO(GDALRasterBandH, GDALRWFlag, int, int, int, int, void*, int
    , int, GDALDataType, int, int)’, declared with attribute warn_unused_result [-Wunused-result]
        0, 0);
             ^
    make[2]: *** [CMakeFiles/aread8.dir/tiffIO.cpp.o] Error 1
    make[1]: *** [CMakeFiles/aread8.dir/all] Error 2
    make: *** [all] Error 2
    vagrant@vagrant-ubuntu-trusty-64:~/TauDEM-Develop/src/build$

Terry

**Comment by dtarb** [comment]
@twilkinson Try pull a copy of the HeaderRefactor branch.  I thought I should try and address the problem that was giving me a warning and you an error and which when I investigated seemed to be due to a forward declaration error.  I have tried to fix this in the new branch, and on my computer no longer get the compiler warning above.  The strategy I took, in case you are curious is described in https://github.com/dtarb/TauDEM/blob/HeaderRefactor/UpdateNotes.txt.  I'll merge this branch into Develop once it has been tested a bit more, but my tests seem to check out so far.

**Comment by twilkinson** [comment]
@dtarb, thanks for this.  The HeaderRefactor branch now works fine for me on both Ubuntu 14.04/C++v4.8.4 and Centos 7.4/C++v5.4.0.  I did have to add the following (from https://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake) near the top of CMakeLists.txt to activate the C++ 11 standard:

    macro(use_cxx11)
      if (CMAKE_VERSION VERSION_LESS "3.1")
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
          set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")
        endif ()
      else ()
        set (CMAKE_CXX_STANDARD 11)
      endif ()
    endmacro(use_cxx11)
    
    use_cxx11()
   
Fyi, using this branch I was also able to remove the `-netlyr logan` switch (issue https://github.com/hydroshare/hydroshare-jupyterhub/issues/113) from the commandline when running `streamnet`, so that issue seems to be fixed too.

AND the additional information in the github README.txt is very useful! Thanks.

**Comment by dtarb** [comment]
Glad it is working.  Looking at that stack overflow answer it seems like the macro you added may be limited to GCC (for CMake versions <3.1).  It would be simpler to just add `set (CMAKE_CXX_STANDARD 11)` and require CMake version >=3.1 (released 12/2014 which may be after Ubuntu 14.04).  Would this be limiting?  The current minimum required version is 2.8.9.  My box has version 3.5.1 (released 3/2016 - which is consistent perhaps with Ubuntu 16.04).  

I think that removing the -netlyr option should have been possible on the Develop branch since commit 951ed55 on Nov 18 https://github.com/dtarb/TauDEM/commits/Develop/src/streamnet.cpp, but perhaps you have not been able to compile since then.

**Comment by twilkinson** [comment]
Yes, it does look like the macro I got from stackoverflow will only work for GCC - luckily that's what I have :-).  No problem upgrading `cmake` though (https://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu), and then simply adding the one line `set (CMAKE_CXX_STANDARD 11)` to `CMakeLists.txt`.

And you are right about the `-netlyr ` option - I've just not been able to compile the Develop branch until now.

Looks all good now.

**Comment by dtarb** [comment]
Thanks.  I updated CMakeLists and merged this branch into develop.
